export const metadata = {
  title: 'ISR',
  description: 'Generated by Next.js',
}

// declaring the whole project revalidates every 60 seconds 
export const revalidate = 60;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
